### ISSUE TITLE
`post-comment` not working?

### ISSUE THREAD

**Issue by ospfranco** [tangro/actions-test#3]
Hey, thanks for the step, but I tried the post-comment option and nothing got posted to one of my PRs.

My config:
```
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Install Dependencies
        run: yarn
      - name: Run tests
        uses: tangro/actions-test@v1.1.6
        with:
          post-comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
```

Any help would be appreciated, thanks!

Edit: I have to say our test set is not exiting cleanly, we have some open handles that cause an exit with 1, could this be part of the problem?

**Comment by ospfranco** [comment]
lol, I just realized that even if the tests don't fail it is this script that fails... any support?

**Comment by ankri** [comment]
Did you check that you have a `test:ci` with `jest --testLocationInResults --ci --outputFile=test_results.json --json` in your `package.json` -> [Documentation](https://github.com/tangro/actions-test#usage)

Otherwise please post the "Raw Logs" of the failing workflow

![image](https://user-images.githubusercontent.com/2842920/100920534-8d6ac900-34db-11eb-9d51-a7aaa3043430.png)

**Comment by ospfranco** [comment]
yes, the command is correct, I forked the project and trying to add debug output and it seems it cannot require the `test_results.json` file, it complains it cannot find it

**Comment by ospfranco** [comment]
Sorry, previous comment is not valid, I was doing some other testing, I added some debug output on the wrapWithSetStatus function's catch block and I get this error:

`ReferenceError: name is not defined`

**Comment by ankri** [comment]
Let me know what you found out. I have created a simple reproduction repo, that works:

**package.json**
```json
"scripts": {
  "test": "jest",
  "test:ci": "jest --testLocationInResults --ci --outputFile=test_results.json --json"
},
"devDependencies": {
  "jest": "26.6.3"
}
```

**test.js**
```js
describe("Test suite", () => {
  it("should fail", () => {
    expect(false).toBe(true);
  });
});
```

**.github/workflows/test.yml**
```yml
name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x
      - name: Run npm install
        run: npm install
      - name: Run tests
        uses: tangro/actions-test@v1.1.6
        with:
          post-comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
```

**Comment by ankri** [comment]
> `ReferenceError: name is not defined`

Do you have some more information? Maybe the log file that the error happened in? Without context it is a bit hard to follow which `name` is supposed to be not defined.

**Comment by ospfranco** [comment]
that is what I'm trying to figure out, but the logs show no error because all the errors are swallowed, trying to get the stack trace currently, I'll let you know what I find

**Comment by ospfranco** [comment]
yeah, it seems to be working on a simple empty project, but on our big project it is not... weird, somewhere a name variable is not being set

**Comment by ankri** [comment]
Maybe remove the `checkRun` stuff in your fork. You don't need it for the comment.

**Comment by ankri** [comment]
just this
```typescript
export async function createChecksFromTestResults({
  pathToTestOutput,
  context
}: {
  pathToTestOutput: string;
  context: GitHubContext<{}>;
}): Promise<FormattedTestResults> {
  const [owner, repo] = context.repository.split('/');

  const formattedTestResults = require(pathToTestOutput) as FormattedTestResults;

  return formattedTestResults;
}

```

**Comment by ospfranco** [comment]
I've managed to narrow it down to the `getCheckRunForAction` function, but not sure exactly what is failing

**Comment by ankri** [comment]
Does your workflow have a name?

```yml
name: Test <--------------
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x
      - name: Run npm install
        run: npm install
      - name: Run tests
        uses: tangro/actions-test@v1.1.6
        with:
          post-comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson(github) }}

```

**Comment by ospfranco** [comment]
yes
```yaml

name: JS Checks
on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x
      - name: Install Dependencies
        run: yarn
      - name: Run tests
        uses: ospfranco/gh-jester@v1.0.9
        with:
          post-comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
    
  flow:
    runs-on: ubuntu-latest

    steps:
      - uses : actions/checkout@v2
      - name: Test using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Install Dependencies
        run: yarn
      - name: Flow
        run: yarn flow

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Install Dependencies
        run: yarn
      - name: Lint
        run: yarn lint

```
